CREATE TABLE LNK_SALES_TXN (
    SALES_TXN_HK    STRING PRIMARY KEY,
    CUSTOMER_HK     STRING,
    MATERIAL_HK     STRING,
    SALES_DOC_HK    STRING,
    ORG_HK          STRING,
    LOAD_DATE       TIMESTAMP,
    RECORD_SOURCE   STRING
);
