CREATE VIEW BV_KPI_UNPIVOTED AS
SELECT 
    st.SALES_TXN_HK,
    st.BUDAT,
    kpi.KPI_NAME,
    kpi.VALUE,
    st.LOAD_DATE
FROM SAT_SALES_FACTS st
LATERAL VIEW EXPLODE(ARRAY(
    NAMED_STRUCT('KPI_NAME', 'Quantity', 'VALUE', st.QUANTITY),
    NAMED_STRUCT('KPI_NAME', 'TGS', 'VALUE', st.TGS),
    NAMED_STRUCT('KPI_NAME', 'TNS', 'VALUE', st.TNS)
)) kpi;
