CREATE TABLE FACT_SALES AS
SELECT
    st.SALES_TXN_HK AS SALES_TXN_KEY,
    st.BUDAT AS DATE_KEY,
    l.CUSTOMER_HK AS CUSTOMER_KEY,
    l.MATERIAL_HK AS MATERIAL_KEY,
    l.ORG_HK AS ORG_KEY,
    st.QUANTITY,
    st.TGS,
    st.TNS
FROM LNK_SALES_TXN l
JOIN SAT_SALES_FACTS st
    ON l.SALES_TXN_HK = st.SALES_TXN_HK;
